spring:
  datasource:
    url: jdbc:sqlite:/run/media/ps/c4cc18ff-fa71-43fb-8a59-06bc37d5c482/water/reception.db
    driver-class-name: org.sqlite.JDBC

flowDir: /run/media/ps/c4cc18ff-fa71-43fb-8a59-06bc37d5c482/water/flow
tideDir: /run/media/ps/c4cc18ff-fa71-43fb-8a59-06bc37d5c482/water/tide